version: 2

jobs:
    build:
        docker:
            - image: alpine:latest
        steps:
            - checkout
            - run: apk add make git vim neovim
            - run: make test
            - run: make test-nvim
